### ISSUE TITLE
Favicon broken in Vivaldi

### ISSUE THREAD

**Issue by emoose** [Dinoosauro/restore-twitter-icon#1]
Thanks for the nice addon, unfortunately the favicon seems to break for me with Vivaldi 6.1.3035.204:

![image](https://github.com/Dinoosauro/restore-twitter-icon/assets/1755499/1139d87d-c8f0-4311-8af6-7013435f5f37)

Not sure if this is a Vivaldi issue or problem with the script, or maybe some issue with my setup itself... would be great if it can be fixed since that new X icon is so much worse now.

Other than this the rest of it seems to work fine.

Thanks again!

E: I tried removing the lone `changeFavicon()` call to see if that worked, but the other `changeFavicon()` call would be ran later on and change it to broken image again some time after it fully loaded, so at least it doesn't seem timing related, for now I just added `return;` to start of that func.

**Comment by dinoosauro** [comment]
Hi! Thank you for letting me know. I made a few changes to the changeFavicon function and now it works on Vivaldi (tested on Linux). In any case, if you still experience the same error, let me know and I'll try to change it in another way

**Comment by emoose** [comment]
Yep that seems to have fixed it for me, thanks for the quick fix!

There is one other odd thing I noticed, not sure if it's Vivaldi specific or not, when I first load in (or refresh page), the icon on the page has some circle border around it:

![image](https://github.com/Dinoosauro/restore-twitter-icon/assets/1755499/d656e5a3-aeaf-41b5-bf4c-1d9a81bb769b)

But if I hover over that icon, or resize page with ctrl+scroll, that border goes away:

![image](https://github.com/Dinoosauro/restore-twitter-icon/assets/1755499/02119468-545e-4334-b915-3c25382057f6)

Not a huge deal, but iirc it didn't used to have that border before, so thought it was worth bringing up.

**Comment by dinoosauro** [comment]
Oh you're right, sorry but I stopped testing on Vivaldi after the tab icon change and I didn't made the login, so I didn't notice that. I should have fixed it now, let me know if it works. Thank you again for reporting this!

**Comment by emoose** [comment]
That did the trick, all looks good now, thanks again!
